### PR TITLE
Feature/fix c sdk integration

### PR DESCRIPTION
**Pull request by LittleMonsterFr**
**Who** : Me
**What** : Modification of the cmakelist to integrate the build of the library in the one of the c-sdk
**Why** : No need to link to the ne10 lib anymore as the files are in

### CODE REVIEW

**Comment by ideoforms** [comment]
Could you add some guidance on how I can validate and test this?

**Comment by LittleMonsterFr** [comment]
@ideoforms
To check the build : Checkout https://github.com/chirp/chirp-engine-c-sdk/tree/feature/neon-as-submodule , upfate submodules and build any of the following platforms : android-arm, android-arm64, raspbian-arm, linux-arm

To test : Run the corresponding sdks with these new built libraries

**Comment by ideoforms** [comment]
I'm looking in the README but it seems to be a bit out of date, no instructions for building android and still references `gomobile` etc. 🤔

**Comment by LittleMonsterFr** [comment]
Will update on the c-sdk branch

**Comment by ideoforms** [comment]
Would you also be able to add subheadings with setup instructions for each platform? e.g., I'm just trying to build for `linux-arm` but getting errors about missing `arm-linux-gnueabihf-gcc`, I assume because I don't have the arm gcc toolchain.

If this is too much for this PR, feel free to create a ticket

**Review by ideoforms — APPROVED** [review]
I'm going to take your word on this one :)

**Pull request merged**
